// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: dltlsdml.proto

package dltlsdml

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Dltlsdml_SayHello_FullMethodName = "/dltlsdml.Dltlsdml/SayHello"
)

// DltlsdmlClient is the client API for Dltlsdml service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type DltlsdmlClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type dltlsdmlClient struct {
	cc grpc.ClientConnInterface
}

func NewDltlsdmlClient(cc grpc.ClientConnInterface) DltlsdmlClient {
	return &dltlsdmlClient{cc}
}

func (c *dltlsdmlClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Dltlsdml_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DltlsdmlServer is the server API for Dltlsdml service.
// All implementations must embed UnimplementedDltlsdmlServer
// for forward compatibility
//
// The greeting service definition.
type DltlsdmlServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDltlsdmlServer()
}

// UnimplementedDltlsdmlServer must be embedded to have forward compatible implementations.
type UnimplementedDltlsdmlServer struct {
}

func (UnimplementedDltlsdmlServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDltlsdmlServer) mustEmbedUnimplementedDltlsdmlServer() {}

// UnsafeDltlsdmlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DltlsdmlServer will
// result in compilation errors.
type UnsafeDltlsdmlServer interface {
	mustEmbedUnimplementedDltlsdmlServer()
}

func RegisterDltlsdmlServer(s grpc.ServiceRegistrar, srv DltlsdmlServer) {
	s.RegisterService(&Dltlsdml_ServiceDesc, srv)
}

func _Dltlsdml_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DltlsdmlServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dltlsdml_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DltlsdmlServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dltlsdml_ServiceDesc is the grpc.ServiceDesc for Dltlsdml service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dltlsdml_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dltlsdml.Dltlsdml",
	HandlerType: (*DltlsdmlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Dltlsdml_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dltlsdml.proto",
}
